---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swift-operator-vsphere

images:
- name: docker.io/swiftinc/ap-vsphere-operator
  newName: registry:5000/swiftinc/ap-vsphere-operator

resources:
- resources/clusterrolebinding_vsphere-admins.yaml
- resources/clusterrole_vsphere-admin.yaml
- resources/clusterrole_vsphere-operator.yaml
- resources/deployment_vsphere-operator.yaml
- resources/rolebinding_vsphere-operator.yaml
- resources/serviceaccount_vsphere-operator.yaml
- resources/service_vsphere-operator-packer.yaml
