---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vsphere-admins
roleRef:
  kind: ClusterRole
  name: vsphere-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: vsphere-operator
  namespace: swift-operator-vsphere
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
