---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsphere-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vsphere-operator
  template:
    metadata:
      labels:
        name: vsphere-operator
    spec:
      serviceAccountName: vsphere-operator
      containers:
      - name: vsphere-operator
        image: docker.io/swiftinc/ap-vsphere-operator@sha256:9ea51477909549803bf48c333ccb743e4c341c857f5e02b0d1f8bfdaf3c53cc1
        imagePullPolicy: Always
        args:
        - "--max-concurrent-reconciles"
        - "5"
        env:
        - name: ANSIBLE_LOG_PATH
          value: stdout
        - name: VMWARE_PORT
          value: "443"
        - name: VMWARE_VALIDATE_CERTS
          value: "true"
        - name: PACKER_CACHE_DIR
          value: /var/tmp
        - name: WATCH_NAMESPACE
          value: ""
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        volumeMounts:
        - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          name: ca-trust
      volumes:
      - name: ca-trust
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
          type: ""
