---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsphere-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vsphere-operator
  template:
    metadata:
      labels:
        name: vsphere-operator
    spec:
      serviceAccountName: vsphere-operator
      containers:
      - name: vsphere-operator
        image: docker.io/swiftinc/ap-vsphere-operator@sha256:edabdf6af7b3ea886fb27f072b8da066b93c8427470624f18e95115377d4409c
        imagePullPolicy: Always
        args:
        - "--max-concurrent-reconciles"
        - "5"
        env:
        - name: VMWARE_PORT
          value: "443"
        - name: VMWARE_VALIDATE_CERTS
          value: "true"
        - name: PACKER_CACHE_DIR
          value: /var/tmp
        - name: WATCH_NAMESPACE
          value: ""
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        volumeMounts:
        - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
          name: ca-trust
      volumes:
      - name: ca-trust
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
          type: ""
